spring:
  datasource:
    url: jdbc:postgresql://47.100.69.147:5432/evaluate?currentSchema=evaluate&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: admin
    password: 123456!
    driver-class-name: org.postgresql.Driver
